# Generated by Django 3.0.2 on 2020-04-16 11:41

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polyglot', '0048_auto_20200226_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.SlugField(allow_unicode=True, max_length=10, unique=True)),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['shortname'],
            },
        ),
        migrations.CreateModel(
            name='LegalFormDelete',
            fields=[
                ('binyan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polyglot.Binyan')),
            ],
            bases=('polyglot.binyan', django.contrib.auth.mixins.LoginRequiredMixin, utils.ObjectDeleteMixin, django.views.generic.base.View),
        ),
        migrations.CreateModel(
            name='LegalFormDetails',
            fields=[
                ('binyan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polyglot.Binyan')),
            ],
            bases=('polyglot.binyan', utils.ObjectDetailsMixin, django.views.generic.base.View),
        ),
        migrations.CreateModel(
            name='LegalFormUpdate',
            fields=[
                ('binyan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polyglot.Binyan')),
            ],
            bases=('polyglot.binyan', django.contrib.auth.mixins.LoginRequiredMixin, utils.ObjectUpdateMixin, django.views.generic.base.View),
        ),
    ]
