# Generated by Django 3.0.2 on 2020-04-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalform',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
